### PR TITLE
Update stage_3_disinfect.bat

### PR DESCRIPTION
**Pull request by RedBaron2**
@vocatus 
I noticed this that last time I ran 'Tron'. It installed malwarebytes on a system that already had it installed.
These just needed to be changed.

### CODE REVIEW

**Comment by vocatus** [comment]
How does switching the order of the two lines change detection?

**Comment by RedBaron2** [comment]
@vocatus 
It isn't just changing the order it is the directory structure that changes. The (2.x) version has the Malwarebytes anti-malware all in one line. The (3.X) version has the Malwarebytes/anti-malware.
The problem lies in detection of the 2.x version and the 3.x version. (Which the script is not detecting now.) It then proceeds to install 2.x which takes over from the 3.x version already installed.
{ This could result in a technician worried about repairing the previous premium version }
This will detect if the 3.x version is installed on a 64 bit system. It is not complete by any means.  It is a quick band-aid for the current version of the script.
The best fix would detect bitness and then check existence of both paths of program files for MBAM.

**Comment by qwertychouskie** [comment]
Your best bet would be to have all 4 lines:
```
if exist "%ProgramFiles%\Malwarebytes Anti-Malware\mbam.exe" set EXISTING_MBAM=yes
if exist "%ProgramFiles%\Malwarebytes\Anti-Malware\mbam.exe" set EXISTING_MBAM=yes
if exist "%ProgramFiles(x86)%\Malwarebytes Anti-Malware\mbam.exe" set EXISTING_MBAM=yes
if exist "%ProgramFiles(x86)%\Malwarebytes\Anti-Malware\mbam.exe" set EXISTING_MBAM=yes
```

**Comment by RedBaron2** [comment]
@qwertychouskie 
That might be the better way, but malwarebytes never installs to the x86 directory structure.
@vocatus 
I have adjusted my PR to be
`if exist "%ProgramFiles%\Malwarebytes\Anti-Malware\mbam.exe" set EXISTING_MBAM=yes`
`if exist "%ProgramFiles%\Malwarebytes Anti-Malware\mbam.exe" set EXISTING_MBAM=yes`
`if exist "%ProgramFiles(x86)%\Malwarebytes Anti-Malware\mbam.exe" set EXISTING_MBAM=yes`

This will fix the issue of detection of mbam on either type of system.

**Comment by vocatus** [comment]
OK, I understand now. Approved. Thank-you.

**Pull request merged**
