### PR TITLE
Link all of (or most of) the things

### PR DESCRIPTION
**Pull request by technicalpickles**
The first time reading about Tron, I wasn't sure what a lot of the tools it uses were and what they did. So, I took a few passes through to link to resources I could find about them, as well as other places that made sense as links (ie /r/tronscript).

A few things to consider:

* many things I couldn't find a home page for, but there were downloads from bleepingcomputer and majorgeeks. Is there a preference one way or the other?
* are there good links for the rest of the Microsoft tools? I found a few of them, but it's not quite complete

I also started to try to give some more beginner instructions for how to get started (ie boot into safe mode), but didn't go much further than that as I wasn't sure if that kind of change would be accepted.

### CODE REVIEW

**Comment by vocatus** [comment]
Hi there,

I pull all the utilities from BleepingComputer, so that could be considered the authoritative source.

As far as the changes in the commit, I see you're using reddit-style markdown syntax to convert a lot of things to links. Does that syntax work on Github? (not familiar with it)

**Comment by ansballard** [comment]
Link syntax is correct according to [Github's markdown page](https://help.github.com/articles/markdown-basics/#links)

**Comment by technicalpickles** [comment]
> t, I see you're using reddit-style markdown syntax to convert a lot of things to links. Does that syntax work on Github? (not familiar with it)

They are just Markdown links, and GitHub supports them (I use them all the time). You can see the rendered version of the changed README here:
https://github.com/technicalpickles/tron/blob/link-all-the-things/README.md

**Comment by ayancey** [comment]
@technicalpickles Is your name really Josh Nichols?

**Comment by technicalpickles** [comment]
@ayancey I don't even know what to say to that...

**Comment by vocatus** [comment]
Right now there are conflicts so I can't quickly merge it, but if you update it based on the current version I'll commit the merge. Thanks for doing this.

**Comment by vocatus** [comment]
Josh, can you update this to be compatible with the current code?
    
    On 2015-08-23 14:26, Josh Nichols
      wrote:
    
    
      The first time reading about Tron, I wasn't sure what a lot of
        the tools it uses were and what they did. So, I took a few
        passes through to link to resources I could find about them, as
        well as other places that made sense as links (ie
        /r/tronscript).
      A few things to consider:
      
        many things I couldn't find a home page for, but there were
          downloads from bleepingcomputer and majorgeeks. Is there a
          preference one way or the other?
        are there good links for the rest of the Microsoft tools? I
          found a few of them, but it's not quite complete
      
      I also started to try to give some more beginner instructions
        for how to get started (ie boot into safe mode), but didn't go
        much further than that as I wasn't sure if that kind of change
        would be accepted.
      
      You can view, comment on, or merge this pull request online
        at:
        https://github.com/bmrf/tron/pull/18
      Commit Summary
      
        Link to subreddit
        Link to Safe Mode section
        Talk about how to boot into safe mode ie press F8, and link
          to microsoft documentation
        Correct capitalization of GitHub, and link to code on
          GitHub.
        link to tools in full description where possible
      
      File Changes
      
         M README.md
          (58) 
      
      Patch Links:
      
        https://github.com/bmrf/tron/pull/18.patch
        https://github.com/bmrf/tron/pull/18.diff

**Comment by vocatus** [comment]
Closing due to no response from requester.

**Pull request closed without merging**
