### PR TITLE
Update stage_2_de-bloat.bat

### PR DESCRIPTION
**Pull request by madbomb122**
changed the GUID total counter (should be better, it also counts the 'for loops' and the' WTA', old one didnt count those)
i had the title change ONLY if verbose = no (dont need it to show if it shows in the command line already)

Title should look like "Tron v.1.4 [GUID: {40F4FF7A-B214-4453-B973-080B09CED019} -- 1/15353]"

Tron v%TRON_VERSION% [GUID: %%i -- !TICKER!/%GUID_TOTAL%]
%%i is Current GUID
!TICKER! is current GUID count
%GUID_TOTAL% is total GUID

### CODE REVIEW

**Comment by vocatus** [comment]
So this will show in the title if `VERBOSE=yes` ? Also, does it display anything to the console window?

**Comment by madbomb122** [comment]
`VERBOSE=no` -the title i did show, nothing else changed
`VERBOSE=yes`-nothing is changed

**Comment by vocatus** [comment]
Quick question, why change the find command to look for `.*` instead of `{` ? Won't that mess up the count since it'll count lines that aren't GUIDs?

**Comment by madbomb122** [comment]
opps that was supposed to be for total # of lines for an old version i was trying out..
also so you know the `{` one does not count the stuff like `if exist %SystemDrive%\dell\dbrm rd /s /q %SystemDrive%\dell\dbrm`

**Comment by vocatus** [comment]
yeah, those should actually be removed anyway. They used to function back when the by_GUID lists were self-executing `.bat` files instead of `.txt`, but since the method for executing the lists changed those lines don't do anything.

**Pull request merged**
