### PR TITLE
Make admin request automatic.

### PR DESCRIPTION
**Pull request by Steetsman**
Just launches a UAC prompt that auto-elevates the prompt. (As long as the user hits yes)

### CODE REVIEW

**Comment by qwertychouskie** [comment]
Seems a dupe of https://github.com/bmrf/tron/pull/80, though maybe @vocatus will change his mind this time ;)

**Comment by vocatus** [comment]
Hi @Steetsman , 

I'm testing the code right now, and it does seem to auto-relaunch correctly, however if Tron is run as an Administrator directly, then the script crashes with no output. Can you duplicate this on your end?

**Comment by kronflux** [comment]
Herein lies the problem. IF there's a failure in attempting to elevate a batch file, there's rarely means of diagnosing the situation. most attempts also break running it manually as admin.
There HAVE been some that work(I've used many in the past myself, and most of the scripts on my github currently have an old version that once worked, and after some windows update no longer work)

I did manage to find this, which I haven't actually tested, but seems pretty solid -for now-
https://gist.github.com/neremin/3a4020c172053d837ab37945d81986f6

**Comment by Steetsman** [comment]
@vocatus I could not replicate that on my end. If the script is launched as admin, the entire section dealing with elevation is automatically bypassed by earlier code I did not write. As for your concerns, @kronflux, They are valid, but as I mentioned, I'm an amateur here, and I did not know (nor could I find) a viable option for detecting administrator elevation status without major edits to integral parts of tron, something I didn't want to do. The solution I would think up would be as follows

Script detects it is not running as admin>Attempts to elevate>Unexpectedly fails>Script displays message stating that elevation request has failed, then asks the user to manually elevate it.>Exit script (Maybe write a var to file disabling the auto-admin section on next launch.)

Other than that, I really don't see a way to automatically fix the issue, as if it failed the first time, it will more than likely fail the second and any subsequent times.

**Comment by kronflux** [comment]
that's kind of my point though. there's no point in adding it if it's unreliable and difficult to diagnose. It makes far more sense that the user elevate it themselves, since there's NO native method to elevate a script using batch, and every method out there is a workaround that launches something else entirely(vbscript or javascript) to perform the task.

In my opinion, it also makes more sense for the user to elevate it manually, because it makes them fully accept the potential consequences of using a script designed for advanced users to repair systems.

but that's just my two cents worth. really up to @vocatus

**Comment by vocatus** [comment]
Hi @kronflux and @Steetsman, apologies for the delay, been traveling for work and feel behind on Tron a bit.

I think I agree with @kronflux that unless we can get it working 100% reliably I'm wary of putting it in. Because Tron supports so many versions of Windows, each with their own weird quirks (XP vs. 10, for example), any workaround/hack method that isn't 100% reliable will likely end up causing problems. I guess for me this is an example of "Is the juice worth the squeeze?" e.g. a significant amount of effort to solve a very small problem (a user not running Tron as admin). 

In general I like forcing the user to run as admin because a. keeps Tron code simpler, and b. teaches people something (how to launch a program explicitly as admin). Teach to fish vs. give fish etc. 

I'll reject this for now, the main reason being something [from the CQ](https://www.reddit.com/r/TronScript/wiki/index#wiki_10._why_is_tron_written_in_batch.3F_why_not_powershell.3F): "Consistent reliability across diverse environments is more important than additional features." Since there's no native, official way to do this on everything from Vista through 10, I'm going to leave it out.

**Pull request closed without merging**
