### PR TITLE
Output display when section is done

### PR DESCRIPTION
**Pull request by madbomb122**
added code to display when it's done with a section of the file
*note: sections in the GUID files still need to be set with :::

### CODE REVIEW

**Comment by madbomb122** [comment]
or instead you can use total number of GUIDs with and use that for some sort of progress

```
set NUM_GUID=0
for /F %%i in ('findstr /R /N "^{" programs_to_target_by_GUID.txt ^| find /C ":"') do set NUM_GUID=%%i
```

**Comment by qwertychouskie** [comment]
Why was this closed?

**Comment by madbomb122** [comment]
2 reasons..
1. The file was changed so i dunno if the changes would be undone if merged
2. Didnt seem like the pull was wanted.. been open for over a week

**Comment by vocatus** [comment]
Don't worry about closing pulls, sometimes I'll go a couple weeks without being able to work on Tron very much but I do get to everything eventually. I'll close/reject if it's not necessary.

As far as this change, I do like it, and I integrated a a version of what you wrote into v10.0.5 (out now). The only difference is instead of outputting to the console, which would push everything off the screen pretty quickly, it just dumps progress to the RAW_LOGS folder. Using `-v` will force it to show output to the console.

Thanks again for the idea.

**Comment by madbomb122** [comment]
yeah i know you did a raw dump version of it in the new version..

also i thought of a way to get the progress to show w/o cluttering the screen... have it display the progress in the title bar

**Comment by madbomb122** [comment]
i found some code that can be used to display progress.. however you cant really use ctrl+c while it's doing it

if you need some help integrating this let me know (i did test it a bit to make sure you can use a counting variable)

`@echo off
set Count=1
setlocal EnableDelayedExpansion

:: Sets BSpace as a backspace
for /F "tokens=1 delims=# " %%a in ('"prompt #$H# & echo on & for %%b in (1) do rem"') do set "BSPACE=%%a"

:: Shows Step 1
<nul set /p =Step 1

:: pings just for a few second pause
ping 127.0.0.1 >nul

:: Deletes the 1 then puts a 2
<nul set /p =%BSPACE%
<nul set /p =2
set /A Count=Count+1
ping 127.0.0.1 >nul

:: Deletes the 2 then puts whatever !Counter! is (which is 3 at this point)
<nul set /p =%BSPACE%
<nul set /p =!Counter!
ping 127.0.0.1 >nul

:: Clears Step & number
<nul set /p =%BSPACE%%BSPACE%%BSPACE%%BSPACE%%BSPACE%%BSPACE%

:: A Pause
pause`

**Pull request closed without merging**
