### PR TITLE
Update metro_3rd_party_modern_apps_to_target_by_name.ps1

### PR DESCRIPTION
**Pull request by madbomb122**
Makes sure Appx removal is finished before script closes

### CODE REVIEW

**Comment by vocatus** [comment]
Hi @madbomb122, have you tested and verified this works?

**Comment by madbomb122** [comment]
it should work, but i'll re-test it today (currently installing win 10 in a virtual machine)

**Comment by madbomb122** [comment]
well on a small scale it works (only few apps in list being removed).. but seems to freeze my VM with the current script.. i'll see if i can fix it

**Comment by madbomb122** [comment]
It's kinda odd that on my initial test with what i wrote in this script it works.

In my win10 script it works perfectly, but since i do things a different way i had to adapt it. which is were there is an issue. Part of it being the wild cards (*s).

**Pull request closed without merging**
