### PR TITLE
Use syntax redirection in place of ERRORLEVEL

### PR DESCRIPTION
**Pull request by nemchik**
This should solve https://github.com/bmrf/tron/issues/61

### CODE REVIEW

**Comment by nemchik** [comment]
I made these changes knowing how the relation between ERRORLEVEL and redirection work, but I have not tested this code. I have multiple other projects where I have done the same thing with no issues.

**Comment by nemchik** [comment]
Another point of discussion is that using syntax redirection might make the code look less human readable in some cases. Personally I don't think ERRORLEVEL is very human readable either, but that's probably just me.

**Comment by vocatus** [comment]
I'll leave things the way they are in the majority of the code, but I'm OK with slowly moving things to the syntax redirection method over time.

**Comment by nemchik** [comment]
No worries, this one was more of a personal vendetta because I just don't trust `ERRORLEVEL` :smile:

**Comment by vocatus** [comment]
@nemchik it's like the friend that's reliable 80% of the time. Just enough unreliability to cause you concern

**Pull request closed without merging**
