### PR TITLE
Shorten the SMART check code (properly this time)

### PR DESCRIPTION
**Pull request by nemchik**
Picking up where https://github.com/bmrf/tron/pull/47 left off.

### CODE REVIEW

**Comment by vocatus** [comment]
Something's still off. When I run it in a test file, this is the output (adding "OK" to the list of codes to trigger the loop):

OK
OK
OK
OK
OK
OK
OK
Invalid attempt to call batch label outside of batch script.
Invalid attempt to call batch label outside of batch script.
Invalid attempt to call batch label outside of batch script.

**Comment by vocatus** [comment]
Here's the test code I used

set WARNINGS_DETECTED=no
set CUR_DATE=2015-12-04

wmic diskdrive get status | for %%i in (OK,Error,Degraded,Unknown,PredFail,Service,Stressed,NonRecover) do (
find /i "%%i" && (
		call :log "%CUR_DATE% %TIME% ^^^! WARNING: SMART check indicates at least one drive with '%%i' status"
		call :log "%CUR_DATE% %TIME% SMART errors can mean a drive is close to failure"
		call :log "%CUR_DATE% %TIME% Recommend you back the system up BEFORE running Tron."
		color 0e
		set WARNINGS_DETECTED=yes&& goto smart_check_complete
	)
)
:smart_check_complete




:log
echo:%~1
goto :eof

**Comment by nemchik** [comment]
I found this article that explains why it's having trouble: https://social.msdn.microsoft.com/Forums/vstudio/en-US/e527303c-9dc6-447a-a1ed-f80c8351bc97/invalid-attempt-to-call-batch-label-outside-of-batch-script?forum=csharpgeneral

So I created a separate file called `log.bat`
```
@echo off
@echo:%~1
REM This might get tricky sending output to the log file, maybe something like this?
::@echo:%~2
REM Now calling log would look like this:
::call log.bat "Text to send" "%LOGPATH%\%LOGFILE%"
REM Instead of the current code, which looks like this
::call :log "Text to send"
REM Otherwise the %LOGPATH% and %LOGFILE% could be defined in the log.bat, but then we're defining a variable in two places, rather than one.
```
And then use this code for `smart.bat` (that's what i called it while testing just this segment of code)
```
@echo off
set WARNINGS_DETECTED=no
set CUR_DATE=2015-12-04

wmic diskdrive get status | for %%i in (OK,Error,Degraded,Unknown,PredFail,Service,Stressed,NonRecover) do @(
	find /i "%%i" >nul && (
		call log.bat "%CUR_DATE% %TIME% ^^^! WARNING: SMART check indicates at least one drive with '%%i' status"
		call log.bat "%CUR_DATE% %TIME% SMART errors can mean a drive is close to failure"
		call log.bat "%CUR_DATE% %TIME% Recommend you back the system up BEFORE running Tron."
		color 0e
		set WARNINGS_DETECTED=yes&& goto smart_check_complete
	)
)
:smart_check_complete

```
The log thing needs to be addressed, but another significant change was >nul on the find command.

**Comment by nemchik** [comment]
Found this also works:
```
@echo off
if "%~1" equ ":log" goto log
set WARNINGS_DETECTED=no
set CUR_DATE=2015-12-04

wmic diskdrive get status | for %%i in (OK,Error,Degraded,Unknown,PredFail,Service,Stressed,NonRecover) do @(
	find /i "%%i" >nul && (
		@call "%~0" :log "%CUR_DATE% %TIME% ^^^! WARNING: SMART check indicates at least one drive with '%%i' status"
		@call "%~0" :log "%CUR_DATE% %TIME% SMART errors can mean a drive is close to failure"
		@call "%~0" :log "%CUR_DATE% %TIME% Recommend you back the system up BEFORE running Tron."
		color 0e
		set WARNINGS_DETECTED=yes&& goto smart_check_complete
	)
)
:smart_check_complete
goto :eof


:log
echo:%~2
goto :eof
```

This would require changing the log code throughout all of TRON, but it is a fairly simple solution and accomplishes the goal.

**Comment by nemchik** [comment]
So after seeing that multiple files contain the log function (the different stage bat files) I actually think it might be smart to make the `log.bat` and replace all calls to the log function with calls to the `log.bat` and define the path and file in the `log.bat` file so that it's a controlled and uniform code that isnt replicated throughout multiple files.

What do you think?
If you like that idea I can make a separate pull request specifically for the `log.bat` idea, and then rebase this to work with the new code.

**Comment by vocatus** [comment]
Ready to tackle this one?

**Comment by nemchik** [comment]
Closing this and continuing on #52 because my git-fu isn't strong enough to fix the messy history yet.

**Pull request closed without merging**
