### PR TITLE
Simplify SSD check

### PR DESCRIPTION
**Pull request by nemchik**
This is quite a bit simpler. I tested and verified this works.

### CODE REVIEW

**Comment by vocatus** [comment]
testing now

**Comment by vocatus** [comment]
Is there a reason for using `findstr` in the first two commands, but `%FIND%` in the last command?

**Comment by vocatus** [comment]
Great work, this is much cleaner. Thanks nemchik

**Comment by nemchik** [comment]
`echo maybe|findstr /i "YES NO MAYBE"&&echo true||echo false` will echo true
`echo maybe|find /i "YES NO MAYBE"&&echo true||echo false` will echo false
This is because `findstr` will search for YES or NO or MAYBE (case insensitive) because they are separated by spaces. On the other hand `find` will search for the exact text `YES NO MAYBE` as a whole.

**Pull request merged**
