### PR TITLE
More temp file cleaning changes

### PR DESCRIPTION
**Pull request by nemchik**
Here's some more changes for the temp file cleanup.

### CODE REVIEW

**Comment by nemchik** [comment]
Some of this is based on https://www.reddit.com/r/TronScript/comments/3lgvzh/my_thoughts_and_tempfile_removal/ and https://www.reddit.com/r/TronScript/comments/3lvjoa/possibly_useful_info_for_tempfilecleanupbat/ and other things I'm adding.

**Comment by nemchik** [comment]
By the way the `%ALLUSERSPROFILE%` stuff is there for the ProgramData folder, which means I think it's for Vista and newer only. On XP/2003 `%ALLUSERSPROFILE%` is treated as a user folder and processed in the per-user-folder code https://github.com/nemchik/tron/blob/tfc/resources/stage_1_tempclean/tempfilecleanup/TempFileCleanup.bat#L75-L127

**Comment by vocatus** [comment]
Can you rebase this to line up with the current code?

**Comment by nemchik** [comment]
Rebase complete.

**Pull request merged**
