### PR TITLE
Use a modular log function

### PR DESCRIPTION
**Pull request by nemchik**
This comes from https://github.com/bmrf/tron/pull/50 and more specifically [this article](https://social.msdn.microsoft.com/Forums/vstudio/en-US/e527303c-9dc6-447a-a1ed-f80c8351bc97/invalid-attempt-to-call-batch-label-outside-of-batch-script?forum=csharpgeneral).

I have tested a dry run of stage 0 and stage 1, but I have not completed a full run. My test was successful and there is no difference in functionality with this code change. This code change will allow the proposed change in the discussion of https://github.com/bmrf/tron/pull/50
It may be desired to replace `call log.bat` with something like `call function\log.bat`.
This type of change may also be applied to other functions, but the log function is a good start.

### CODE REVIEW

**Comment by vocatus** [comment]
Let me mull this over

**Comment by vocatus** [comment]
My concern is that the logging function is called a *lot*, and putting it into a separate file that must be read from disk every time may end up eating up any speed gains we get from shortening the SMART check code. Thoughts?

**Comment by nemchik** [comment]
Honestly I think the SMART check code is one case of a potential many that Tron could run into in the future. I agree that there may be a performance hit on disk io, but loading a 3 line bat file a couple hundred times is nothing compared to some of the tools Tron already includes.

**Comment by nemchik** [comment]
One of the main advantages is the log file being the same code across all parts of Tron. Currently the log function exists in multiple files and changing something about how Tron acts on its need to log output means changing the same code multiple times.

**Comment by staticextasy** [comment]
I agree with nemchik on the statement of "loading a 3 line bat file a couple hundred times is nothing compared to some of the tools Tron already includes." Clearly you can see that is true. 

The reasoning as well, changing one file versus change multiple means less overhead when you need to make a change.

**Comment by vocatus** [comment]
I've read all comments; thoughts so far:

I understand the argument to just have a single piece of code in a separate file to handle logging, it reduces complexity (good).

Counter-thought is that logging code doesn't change very often (if ever) and it's easy to do a find/replace across the different files if a change is needed. Thoughts on this?

So as I see it, for this change:
Benefit: No discernible benefit to end-users. Reduction of complexity for developers (us) is the primary benefit.
Penalty: Slight increase in runtime

If we do the change, where is the most logical location for function files? `\resources\functions`?

**Comment by nemchik** [comment]
Re- Find/Replace: I am a huge fan, when it works, but if you (or any dev) is ever in a hurry to make a change and doesn't catch something where find/replace failed to accurately make the needed change to a file then you end up with code inconsistencies and possibly breakage for the users. An example of this would be the log code should exist in let's say 8 files, and 7 of them get changes but one is missed. If the one that was missed calls a function that got renamed or does something different than the currently desired behavior this breaks the user experience. So really this change doesn't benefit the user now, but it protects the user later.

Re- Penalty: Another thing to consider is that once the bat file is loaded from disk into the memory of the OS it will be "cached" in memory in some way and so the "couple hundred calls" I mentioned is really a lot less intense than I made it sound. 

Re- Similar Changes: Yes, any function that is called multiple places in Tron could be made into a separate function.bat . There is no end-user benefit to this, but for any dev looking to help out on the project if we want to know where a function is we have one common place to look. There would not be a need to redefine any functions for use in multiple files (which is how the log function is currently setup). This opens up various functions in Tron to be available to be called anywhere during the full run. An example I can think of is `set_cur_date` would be usable in between the KVRT and SVRT tools, rather than just before and after.

Re- `\resources\functions`: I can update the PR to reflect this change.

Extra Thought: Really the goal of this change isn't to cater to the SMART check. This change is meant to resolve the issue presented by the article in the OP where CMD/BAT has trouble reusing pre-existing functions through a pipe `|` because certain actions in CMD/BAT end up creating a separate process that cannot see the functions from the parent process unless the functions are called from an external file. (That's my half understood explanation of the article).

**Comment by vocatus** [comment]
That all makes sense to me. I agree. Let's go ahead and do it.

If you can update the pull request to call `\functions\log.bat` and create log.bat under that directory I'll go ahead and approve it.

**Comment by nemchik** [comment]
PR updated. I tested just to make sure it's working as expected.

**Pull request merged**
