### PR TITLE
real time progress update (w/o line clutter)

### PR DESCRIPTION
**Pull request by madbomb122**
not sure how well this works when tron actually runs.. i have tested the code with a stripped version (w/o it actually trying to uninstall and doing the logs) of this file (using the 3 txt files)

### CODE REVIEW

**Comment by madbomb122** [comment]
btw forgot to mention, any sort of output will mess up the progress display :(

**Comment by madbomb122** [comment]
have an idea of how to fix mess up of the progress if there is an output..
can have it delete the progress shown if it finds a guid the progress shows again at beginning of loop

**Comment by vocatus** [comment]
@madbomb122 just wanted to let you know I haven't forgot about this, just been busy with other things.

**Comment by madbomb122** [comment]
np, plus i'm sure the code needs some testing by people other than me

**Comment by vocatus** [comment]
@madbomb122 have you tested it yourself? If you could post a couple screenshots it'd be super helpful just so I can get a visual for what it'd look like.

**Comment by madbomb122** [comment]
i did some test.. but with it doing no changes (just display).. only problem i could see was if some random display happens (like the "ERROR: Shutting down" thing)

**Comment by vocatus** [comment]
does it break the script if that happens? My #1 concern is that the script doesn't break during runtime.

**Comment by madbomb122** [comment]
dont think it would break the script, think it would just mess up the progress counter

**Comment by madbomb122** [comment]
ugh, cant find the file i used to test the code, so i had to use what i pushed with some edits (so i could run just that w/o it doing changes), but for some reason it's not completely displaying/working properly

**Comment by madbomb122** [comment]
i fixed the problem, but i had it do a random echo on the screen and it just messes up the echo :(

but there is at least another method to do a real time update of progress.. do it with changing the title

so instead of echo "on / out of"
it would be title "on / out of"

**Comment by madbomb122** [comment]
`
:: for total # of lines
for /f %%a in ('findstr /R /N "^.*" stage_2_de-bloat\oem\programs_to_target_by_GUID.txt ^| FIND /C ":"') do set TOTAL_LINES=%%a

:: for the line counter
set /A LINE_COUNT=!LINE_COUNT! + 1

:: for the progress
title Program GUID, Total Lines: !TOTAL_LINES! on !LINE_COUNT!  
`
not sure how well this works or if something like this is fine for you

**Comment by kronflux** [comment]
I can say, as someone in a computer repair/tech environment running this, that the actual GUID number we're on would be more useful than line number.
Professional tools do not rely on the user to open up database files and search line numbers.
I get what you're saying about it for debugging purposes, especially if it hangs on one, but tbh I've never had it hang before.

**Comment by madbomb122** [comment]
@kronflux with a little change to the code i have above it can show all the important stuff
Current line, Total line.. or the % progress, with the current GUID it's on

**Comment by vocatus** [comment]
@madbomb122 @kronflux I like the idea of changing the title for each count. If you can cancel this request and put in a new one with just those changes I'll test and approve it.

**Pull request closed without merging**
